Repository canonical/microstack.run, pull requests merged in 2020-03, with the labels that each got.

#22 Added the additional parameters to the quick-run steps to allow this to work on macOS and Windows 10 from the host side, as intended.
  index.html
Labels: Docs 📚

#29 Downgrade to ruby 2.5
  Dockerfile
Labels: Review: Code +1

#31 Replace sass-lint with stylelint
  .stylelintrc
  _sass/_blockquote.scss
  _sass/_docs.scss
  _sass/_settings.scss
  _sass/_sidebar.scss
  _sass/styles.scss
  package.json
  run
  yarn.lock
Labels: Review: Code +1, Review: QA +1
