Repository canonical/microstack.run, pull requests merged in 2020-09, with the labels that each got.

#55 Flask conversion + Add discourse module
  .env
  .eslintrc.js
  .github/workflows/pr.yaml
  .gitignore
  .prettierignore
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  _config.yml
  _layouts/base.html
  docs/clustering.md
  docs/docs-contrib.md
  docs/index.md
  docs/juju.md
  docs/pro-tips.md
  docs/releases.md
  entrypoint
  nginx.conf
  package.json
  requirements.txt
  run
  static/js/build/copyToClipboard.js
  static/js/build/global-nav.js
  static/js/build/installVersion.js
  static/js/build/osSelector.js
  static/js/build/tabs.js
  static/js/copy-to-clipboard.js
  static/js/global-nav.js
  static/js/installversion.js
  static/js/osselector.js
  static/js/sample.test.js
  static/js/tabs.js
  static/sass/_blockquote.scss
  static/sass/_docs.scss
  static/sass/_pattern_separator.scss
  static/sass/_settings.scss
  static/sass/_sidebar.scss
  static/sass/styles.scss
  templates/400.html
  templates/500.html
  templates/base_layout.html
  templates/docs.html
  templates/docs/docs.html
  templates/docs/document.html
  templates/index.html
  templates/partial/_footer.html
  templates/partial/_navigation.html
  tests/__init__.py
  tests/test_routes.py
  webapp/__init__.py
  webapp/app.py
  webpack.config.js
  yarn.lock
Labels: Project, Review: Code +1, Review: QA +1

#56 Add run file
  requirements.txt
  run
Labels: Review: Code +1, Review: QA +1

#57 Copy update - "MicroStack - OpenStack in a snap"
  run
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#58 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1
