Repository canonical/microstack.run, pull requests merged in 2020-04, with the labels that each got.

#34 Disable renovate for ruby
  renovate.json
Labels: Review: Code +1

#35 Add preview notice
  index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#36 Add HR to buttom of docs layout
  _layouts/docs.html
Labels: Review: Code +1, Review: QA +1
